# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zipcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 476)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 591, 51))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(220, 200, 321, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.continue_button = QtWidgets.QPushButton(Form)
        self.continue_button.setGeometry(QtCore.QRect(680, 410, 101, 41))
        self.continue_button.setObjectName("continue_button")
        self.enter_button = QtWidgets.QPushButton(Form)
        self.enter_button.setGeometry(QtCore.QRect(540, 200, 62, 51))
        self.enter_button.setObjectName("enter_button")

        self.continue_button.clicked.connect(self)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def getZipcode(self):
        print(self.lineEdit.text())

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#00aa7f;\">Please Enter Your Zipcode</span></p></body></html>"))
        self.continue_button.setText(_translate("Form", "Continue"))
        self.enter_button.setText(_translate("Form", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
